configName: lcc_rgb565_mxt_mzef_cu
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFM144
projectName: ''
settings:
  PackageFilter: gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx;bsp;usb;gfx;csp;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;core;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: ./dev_packs/arm/CMSIS/5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/PIC32MZ-EF_DFP/1.3.57/atdf/PIC32MZ2048EFM144.atdf
