configName: lcc_rgb565_mxt_mzef_cu
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFM144
projectName: ''
settings:
  PackageFilter: bsp;core;core_apps_pic32mz_da;core_apps_sam_e70_s70_v70_v71;csp;csp_apps_pic32mz_da;csp_apps_sam_e70_s70_v70_v71;Devices;dev_packs;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_ef;gfx_apps_sam_9x60;harmony-services;quick_docs;touch;usb;usb_apps_device;usb_apps_host
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFM144.atdf
