format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_legato}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: driverInitName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_legato, value: lccDisplayDriver}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: gfx_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_lcc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver_lcc}
- type: ElementPosition
  attributes: {x: '327', y: '572', id: gfx_legato}
